<div class="cat">Browse by category's</div>
<ul class="BByC">
    <?php
    $obj = new Mage_Catalog_Block_Navigation();
    $storeCategories = $obj->getStoreCategories();
    Mage::registry('current_category') ? $currentCategoryId = Mage::registry('current_category')->getId() : $currentCategoryId = '';
    foreach ($storeCategories as $_category):
        ?>
    <li class="BByCLi">
            <strong class="filterName"><?php echo $_category->getName(); ?></strong>
            <?php $categoryChildren = $_category->getChildren(); ?>
            <?php if ($categoryChildren->count()) : ?>
            <ul class="filterContent" style="display: none;">
                    <?php foreach ($categoryChildren as $_categoryChild) : ?>
                        <?php $_categoryChildModel = Mage::getModel('catalog/category')->load($_categoryChild->getId()); ?>
                        <?php $categoryGrandchildren = $_categoryChild->getChildren(); ?>
                        <li>
                            <?php
                            $currentCategoryId === $_categoryChild->getId() ? $bold = "style=\"font-weight:bold\"" : $bold = '';
                            echo '&emsp;' . '<a href="' . $_categoryChildModel->getUrl() . '"' . $bold . '>' . $_categoryChild->getName() . '(' . $_categoryChildModel->getProductCollection()->count() . ')</a>';
                            ?>
                        </li>
                        <?php if ($categoryGrandchildren->count()) : ?>
                            <?php foreach ($categoryGrandchildren as $_categoryGrandchild) : ?>
                                <?php $_categoryGrandchildModel = Mage::getModel('catalog/category')->load($_categoryGrandchild->getId()); ?>
                                <li>
                                    <?php
                                    $currentCategoryId === $_categoryChild->getId() ? $bold = "style=\"font-weight:bold\"" : $bold = '';
                                    echo '&emsp;&emsp;' . '<a href="' . $_categoryGrandchildModel->getUrl() . '"' . $bold . '>' . $_categoryGrandchild->getName() . '(' . $_categoryGrandchildModel->getProductCount() . ')</a>';
                                    ?>
                                </li>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </li>
    <?php endforeach ?>


        <script src="http://code.jquery.com/jquery-1.11.3.min.js" type="text/javascript"></script>
    <script type="text/javascript">


 jQuery('.filterName').click(function () {
                jQuery(this).find('.fa-angle-right').toggleClass('activeFilter');
                jQuery(this).next('.filterContent').toggle();
        });

//
//        var windowWidth = jQuery(window).width();
//        jQuery('.block-subtitle').click(function () {
//            jQuery(this).find('.fa-angle-right').toggleClass('activeFilter');
//            jQuery('#narrow-by-list').toggle();
//        });
////        jQuery('.filterName').click(function () {
////            var windowWidth = jQuery(window).width();
////            if (windowWidth <= 768) {
////                jQuery(this).find('.fa-angle-right').toggleClass('activeFilter');
////                jQuery(this).next('.filterContent').toggle();
////            }
////       



    </script>